<a href="https://colab.research.google.com/github/hewettac/OOP-New/blob/main/ML_1_20_26.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import numpy as np
import pandas as pd

np.random.seed(0)

df=pd.read_csv('dataset1.csv')
x=df[['A','B']]
y=df['C']

class Layer_Dense:
  def __init__(self, n_inputs, n_neurons):
    self.weights=0.1 * np.random.randn(n_inputs, n_neurons)
    self.biases=np.zeros((1, n_neurons))
  def forward(self, inputs):
    self.output=np.dot(inputs, self.weights) + self.biases

class Activation_ReLu:
  def forward(self, inputs):
    self.output=np.maximum(0,inputs)

layer1 = Layer_Dense(2,5)
aa = Activation_ReLu()

layer1.forward(x)
print(layer1.output)
aa.forward(layer1.output)
print(aa.output)

layer2 = Layer_Dense(5,8)
bb = Activation_ReLu()

layer2.forward(aa.output)
print(layer2.output)
bb.forward(layer2.output)
print(bb.output)

layer3 = Layer_Dense(8,2)
cc = Activation_ReLu()

layer3.forward(bb.output)
print(layer3.output)
cc.forward(layer3.output)
print(cc.output)



[[-6.44508184  8.38089992 -0.29266257  1.37385484  5.31658541]
 [ 9.4140567   4.59620753  6.04394676 14.34904621 13.00138379]
 [ 0.25584099  8.84633913  3.07339427  8.86169937 11.10998812]
 [14.07679417  4.71648266  8.31825609 19.36158633 16.78153257]
 [-5.68230988  7.85086259 -0.10397444  1.65987548  5.2569821 ]
 [12.18434159  8.03687564  8.51902961 20.59991124 19.40273837]
 [ 3.24234957  4.25081548  2.97151132  7.53346964  7.76824847]
 [-2.97660426  8.81615637  1.51447297  5.43842826  8.55501024]
 [ 0.82487515  0.89017882  0.69217606  1.73078325  1.74040549]
 [10.21245327  2.55094521  5.74428266 13.2006261  11.10071184]]
[[ 0.          8.38089992  0.          1.37385484  5.31658541]
 [ 9.4140567   4.59620753  6.04394676 14.34904621 13.00138379]
 [ 0.25584099  8.84633913  3.07339427  8.86169937 11.10998812]
 [14.07679417  4.71648266  8.31825609 19.36158633 16.78153257]
 [ 0.          7.85086259  0.          1.65987548  5.2569821 ]
 [12.18434159  8.03687564  8.51902961 20.59991124 19.4